name: Appsec360

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '39 10 * * 2'

jobs:
  Scan-Build:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Credscan
      uses: zricethezav/gitleaks-action@master
      with:
          path: my_file1.txt

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        path: my_file2.txt
        
